// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: operation.proto

package ressources.java.dz.example.grpc;

public interface OperandsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ressources.java.dz.example.grpc.Operands)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 a = 1;</code>
   * @return The a.
   */
  int getA();

  /**
   * <code>int32 b = 2;</code>
   * @return The b.
   */
  int getB();
}
