// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: operation.proto

package ressources.java.dz.example.grpc;

/**
 * Protobuf type {@code ressources.java.dz.example.grpc.Points}
 */
public final class Points extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ressources.java.dz.example.grpc.Points)
    PointsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Points.newBuilder() to construct.
  private Points(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Points() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Points();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ressources.java.dz.example.grpc.Operation.internal_static_ressources_java_dz_example_grpc_Points_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ressources.java.dz.example.grpc.Operation.internal_static_ressources_java_dz_example_grpc_Points_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ressources.java.dz.example.grpc.Points.class, ressources.java.dz.example.grpc.Points.Builder.class);
  }

  private int bitField0_;
  public static final int P1_FIELD_NUMBER = 1;
  private ressources.java.dz.example.grpc.Point p1_;
  /**
   * <code>.ressources.java.dz.example.grpc.Point p1 = 1;</code>
   * @return Whether the p1 field is set.
   */
  @java.lang.Override
  public boolean hasP1() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.ressources.java.dz.example.grpc.Point p1 = 1;</code>
   * @return The p1.
   */
  @java.lang.Override
  public ressources.java.dz.example.grpc.Point getP1() {
    return p1_ == null ? ressources.java.dz.example.grpc.Point.getDefaultInstance() : p1_;
  }
  /**
   * <code>.ressources.java.dz.example.grpc.Point p1 = 1;</code>
   */
  @java.lang.Override
  public ressources.java.dz.example.grpc.PointOrBuilder getP1OrBuilder() {
    return p1_ == null ? ressources.java.dz.example.grpc.Point.getDefaultInstance() : p1_;
  }

  public static final int P2_FIELD_NUMBER = 2;
  private ressources.java.dz.example.grpc.Point p2_;
  /**
   * <code>.ressources.java.dz.example.grpc.Point p2 = 2;</code>
   * @return Whether the p2 field is set.
   */
  @java.lang.Override
  public boolean hasP2() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.ressources.java.dz.example.grpc.Point p2 = 2;</code>
   * @return The p2.
   */
  @java.lang.Override
  public ressources.java.dz.example.grpc.Point getP2() {
    return p2_ == null ? ressources.java.dz.example.grpc.Point.getDefaultInstance() : p2_;
  }
  /**
   * <code>.ressources.java.dz.example.grpc.Point p2 = 2;</code>
   */
  @java.lang.Override
  public ressources.java.dz.example.grpc.PointOrBuilder getP2OrBuilder() {
    return p2_ == null ? ressources.java.dz.example.grpc.Point.getDefaultInstance() : p2_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getP1());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getP2());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getP1());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getP2());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ressources.java.dz.example.grpc.Points)) {
      return super.equals(obj);
    }
    ressources.java.dz.example.grpc.Points other = (ressources.java.dz.example.grpc.Points) obj;

    if (hasP1() != other.hasP1()) return false;
    if (hasP1()) {
      if (!getP1()
          .equals(other.getP1())) return false;
    }
    if (hasP2() != other.hasP2()) return false;
    if (hasP2()) {
      if (!getP2()
          .equals(other.getP2())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasP1()) {
      hash = (37 * hash) + P1_FIELD_NUMBER;
      hash = (53 * hash) + getP1().hashCode();
    }
    if (hasP2()) {
      hash = (37 * hash) + P2_FIELD_NUMBER;
      hash = (53 * hash) + getP2().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ressources.java.dz.example.grpc.Points parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ressources.java.dz.example.grpc.Points parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ressources.java.dz.example.grpc.Points parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ressources.java.dz.example.grpc.Points parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ressources.java.dz.example.grpc.Points parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ressources.java.dz.example.grpc.Points parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ressources.java.dz.example.grpc.Points parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ressources.java.dz.example.grpc.Points parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static ressources.java.dz.example.grpc.Points parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static ressources.java.dz.example.grpc.Points parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ressources.java.dz.example.grpc.Points parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ressources.java.dz.example.grpc.Points parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ressources.java.dz.example.grpc.Points prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ressources.java.dz.example.grpc.Points}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ressources.java.dz.example.grpc.Points)
      ressources.java.dz.example.grpc.PointsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ressources.java.dz.example.grpc.Operation.internal_static_ressources_java_dz_example_grpc_Points_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ressources.java.dz.example.grpc.Operation.internal_static_ressources_java_dz_example_grpc_Points_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ressources.java.dz.example.grpc.Points.class, ressources.java.dz.example.grpc.Points.Builder.class);
    }

    // Construct using ressources.java.dz.example.grpc.Points.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getP1FieldBuilder();
        getP2FieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      p1_ = null;
      if (p1Builder_ != null) {
        p1Builder_.dispose();
        p1Builder_ = null;
      }
      p2_ = null;
      if (p2Builder_ != null) {
        p2Builder_.dispose();
        p2Builder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ressources.java.dz.example.grpc.Operation.internal_static_ressources_java_dz_example_grpc_Points_descriptor;
    }

    @java.lang.Override
    public ressources.java.dz.example.grpc.Points getDefaultInstanceForType() {
      return ressources.java.dz.example.grpc.Points.getDefaultInstance();
    }

    @java.lang.Override
    public ressources.java.dz.example.grpc.Points build() {
      ressources.java.dz.example.grpc.Points result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ressources.java.dz.example.grpc.Points buildPartial() {
      ressources.java.dz.example.grpc.Points result = new ressources.java.dz.example.grpc.Points(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(ressources.java.dz.example.grpc.Points result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.p1_ = p1Builder_ == null
            ? p1_
            : p1Builder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.p2_ = p2Builder_ == null
            ? p2_
            : p2Builder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ressources.java.dz.example.grpc.Points) {
        return mergeFrom((ressources.java.dz.example.grpc.Points)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ressources.java.dz.example.grpc.Points other) {
      if (other == ressources.java.dz.example.grpc.Points.getDefaultInstance()) return this;
      if (other.hasP1()) {
        mergeP1(other.getP1());
      }
      if (other.hasP2()) {
        mergeP2(other.getP2());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getP1FieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getP2FieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private ressources.java.dz.example.grpc.Point p1_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ressources.java.dz.example.grpc.Point, ressources.java.dz.example.grpc.Point.Builder, ressources.java.dz.example.grpc.PointOrBuilder> p1Builder_;
    /**
     * <code>.ressources.java.dz.example.grpc.Point p1 = 1;</code>
     * @return Whether the p1 field is set.
     */
    public boolean hasP1() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.ressources.java.dz.example.grpc.Point p1 = 1;</code>
     * @return The p1.
     */
    public ressources.java.dz.example.grpc.Point getP1() {
      if (p1Builder_ == null) {
        return p1_ == null ? ressources.java.dz.example.grpc.Point.getDefaultInstance() : p1_;
      } else {
        return p1Builder_.getMessage();
      }
    }
    /**
     * <code>.ressources.java.dz.example.grpc.Point p1 = 1;</code>
     */
    public Builder setP1(ressources.java.dz.example.grpc.Point value) {
      if (p1Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        p1_ = value;
      } else {
        p1Builder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.ressources.java.dz.example.grpc.Point p1 = 1;</code>
     */
    public Builder setP1(
        ressources.java.dz.example.grpc.Point.Builder builderForValue) {
      if (p1Builder_ == null) {
        p1_ = builderForValue.build();
      } else {
        p1Builder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.ressources.java.dz.example.grpc.Point p1 = 1;</code>
     */
    public Builder mergeP1(ressources.java.dz.example.grpc.Point value) {
      if (p1Builder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          p1_ != null &&
          p1_ != ressources.java.dz.example.grpc.Point.getDefaultInstance()) {
          getP1Builder().mergeFrom(value);
        } else {
          p1_ = value;
        }
      } else {
        p1Builder_.mergeFrom(value);
      }
      if (p1_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.ressources.java.dz.example.grpc.Point p1 = 1;</code>
     */
    public Builder clearP1() {
      bitField0_ = (bitField0_ & ~0x00000001);
      p1_ = null;
      if (p1Builder_ != null) {
        p1Builder_.dispose();
        p1Builder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.ressources.java.dz.example.grpc.Point p1 = 1;</code>
     */
    public ressources.java.dz.example.grpc.Point.Builder getP1Builder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getP1FieldBuilder().getBuilder();
    }
    /**
     * <code>.ressources.java.dz.example.grpc.Point p1 = 1;</code>
     */
    public ressources.java.dz.example.grpc.PointOrBuilder getP1OrBuilder() {
      if (p1Builder_ != null) {
        return p1Builder_.getMessageOrBuilder();
      } else {
        return p1_ == null ?
            ressources.java.dz.example.grpc.Point.getDefaultInstance() : p1_;
      }
    }
    /**
     * <code>.ressources.java.dz.example.grpc.Point p1 = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ressources.java.dz.example.grpc.Point, ressources.java.dz.example.grpc.Point.Builder, ressources.java.dz.example.grpc.PointOrBuilder> 
        getP1FieldBuilder() {
      if (p1Builder_ == null) {
        p1Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ressources.java.dz.example.grpc.Point, ressources.java.dz.example.grpc.Point.Builder, ressources.java.dz.example.grpc.PointOrBuilder>(
                getP1(),
                getParentForChildren(),
                isClean());
        p1_ = null;
      }
      return p1Builder_;
    }

    private ressources.java.dz.example.grpc.Point p2_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ressources.java.dz.example.grpc.Point, ressources.java.dz.example.grpc.Point.Builder, ressources.java.dz.example.grpc.PointOrBuilder> p2Builder_;
    /**
     * <code>.ressources.java.dz.example.grpc.Point p2 = 2;</code>
     * @return Whether the p2 field is set.
     */
    public boolean hasP2() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.ressources.java.dz.example.grpc.Point p2 = 2;</code>
     * @return The p2.
     */
    public ressources.java.dz.example.grpc.Point getP2() {
      if (p2Builder_ == null) {
        return p2_ == null ? ressources.java.dz.example.grpc.Point.getDefaultInstance() : p2_;
      } else {
        return p2Builder_.getMessage();
      }
    }
    /**
     * <code>.ressources.java.dz.example.grpc.Point p2 = 2;</code>
     */
    public Builder setP2(ressources.java.dz.example.grpc.Point value) {
      if (p2Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        p2_ = value;
      } else {
        p2Builder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.ressources.java.dz.example.grpc.Point p2 = 2;</code>
     */
    public Builder setP2(
        ressources.java.dz.example.grpc.Point.Builder builderForValue) {
      if (p2Builder_ == null) {
        p2_ = builderForValue.build();
      } else {
        p2Builder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.ressources.java.dz.example.grpc.Point p2 = 2;</code>
     */
    public Builder mergeP2(ressources.java.dz.example.grpc.Point value) {
      if (p2Builder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          p2_ != null &&
          p2_ != ressources.java.dz.example.grpc.Point.getDefaultInstance()) {
          getP2Builder().mergeFrom(value);
        } else {
          p2_ = value;
        }
      } else {
        p2Builder_.mergeFrom(value);
      }
      if (p2_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.ressources.java.dz.example.grpc.Point p2 = 2;</code>
     */
    public Builder clearP2() {
      bitField0_ = (bitField0_ & ~0x00000002);
      p2_ = null;
      if (p2Builder_ != null) {
        p2Builder_.dispose();
        p2Builder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.ressources.java.dz.example.grpc.Point p2 = 2;</code>
     */
    public ressources.java.dz.example.grpc.Point.Builder getP2Builder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getP2FieldBuilder().getBuilder();
    }
    /**
     * <code>.ressources.java.dz.example.grpc.Point p2 = 2;</code>
     */
    public ressources.java.dz.example.grpc.PointOrBuilder getP2OrBuilder() {
      if (p2Builder_ != null) {
        return p2Builder_.getMessageOrBuilder();
      } else {
        return p2_ == null ?
            ressources.java.dz.example.grpc.Point.getDefaultInstance() : p2_;
      }
    }
    /**
     * <code>.ressources.java.dz.example.grpc.Point p2 = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ressources.java.dz.example.grpc.Point, ressources.java.dz.example.grpc.Point.Builder, ressources.java.dz.example.grpc.PointOrBuilder> 
        getP2FieldBuilder() {
      if (p2Builder_ == null) {
        p2Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ressources.java.dz.example.grpc.Point, ressources.java.dz.example.grpc.Point.Builder, ressources.java.dz.example.grpc.PointOrBuilder>(
                getP2(),
                getParentForChildren(),
                isClean());
        p2_ = null;
      }
      return p2Builder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ressources.java.dz.example.grpc.Points)
  }

  // @@protoc_insertion_point(class_scope:ressources.java.dz.example.grpc.Points)
  private static final ressources.java.dz.example.grpc.Points DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ressources.java.dz.example.grpc.Points();
  }

  public static ressources.java.dz.example.grpc.Points getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Points>
      PARSER = new com.google.protobuf.AbstractParser<Points>() {
    @java.lang.Override
    public Points parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Points> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Points> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ressources.java.dz.example.grpc.Points getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

