// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: operation.proto

package ressources.java.dz.example.grpc;

public interface PointsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ressources.java.dz.example.grpc.Points)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ressources.java.dz.example.grpc.Point p1 = 1;</code>
   * @return Whether the p1 field is set.
   */
  boolean hasP1();
  /**
   * <code>.ressources.java.dz.example.grpc.Point p1 = 1;</code>
   * @return The p1.
   */
  ressources.java.dz.example.grpc.Point getP1();
  /**
   * <code>.ressources.java.dz.example.grpc.Point p1 = 1;</code>
   */
  ressources.java.dz.example.grpc.PointOrBuilder getP1OrBuilder();

  /**
   * <code>.ressources.java.dz.example.grpc.Point p2 = 2;</code>
   * @return Whether the p2 field is set.
   */
  boolean hasP2();
  /**
   * <code>.ressources.java.dz.example.grpc.Point p2 = 2;</code>
   * @return The p2.
   */
  ressources.java.dz.example.grpc.Point getP2();
  /**
   * <code>.ressources.java.dz.example.grpc.Point p2 = 2;</code>
   */
  ressources.java.dz.example.grpc.PointOrBuilder getP2OrBuilder();
}
