// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: operation.proto

package ressources.java.dz.example.grpc;

public interface ResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ressources.java.dz.example.grpc.Result)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float res = 1;</code>
   * @return The res.
   */
  float getRes();
}
