package services;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Addition.proto

public interface OperandsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Operands)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 a = 1;</code>
   * @return The a.
   */
  int getA();

  /**
   * <code>int32 b = 2;</code>
   * @return The b.
   */
  int getB();
}
