package services;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Addition.proto

public interface ResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Result)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sum = 1;</code>
   * @return The sum.
   */
  int getSum();
}
