# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: operation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0foperation.proto\x12\x1fressources.java.dz.example.grpc\" \n\x08Operands\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x15\n\x06Result\x12\x0b\n\x03res\x18\x01 \x01(\x02\"p\n\x06Points\x12\x32\n\x02p1\x18\x01 \x01(\x0b\x32&.ressources.java.dz.example.grpc.Point\x12\x32\n\x02p2\x18\x02 \x01(\x0b\x32&.ressources.java.dz.example.grpc.Point\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x32\xe1\x03\n\nOperations\x12Y\n\x03\x61\x64\x64\x12).ressources.java.dz.example.grpc.Operands\x1a\'.ressources.java.dz.example.grpc.Result\x12_\n\tsubstract\x12).ressources.java.dz.example.grpc.Operands\x1a\'.ressources.java.dz.example.grpc.Result\x12\\\n\x06multip\x12).ressources.java.dz.example.grpc.Operands\x1a\'.ressources.java.dz.example.grpc.Result\x12\\\n\x06\x64ivide\x12).ressources.java.dz.example.grpc.Operands\x1a\'.ressources.java.dz.example.grpc.Result\x12[\n\x07\x64istace\x12\'.ressources.java.dz.example.grpc.Points\x1a\'.ressources.java.dz.example.grpc.ResultB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'operation_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _globals['_OPERANDS']._serialized_start=52
  _globals['_OPERANDS']._serialized_end=84
  _globals['_RESULT']._serialized_start=86
  _globals['_RESULT']._serialized_end=107
  _globals['_POINTS']._serialized_start=109
  _globals['_POINTS']._serialized_end=221
  _globals['_POINT']._serialized_start=223
  _globals['_POINT']._serialized_end=252
  _globals['_OPERATIONS']._serialized_start=255
  _globals['_OPERATIONS']._serialized_end=736
# @@protoc_insertion_point(module_scope)
